default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: batting_average
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: batting_average
  username: postgres
  password: postgres
  host: localhost
  port: 5432